# Generated by Django 3.2.16 on 2022-10-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mantra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantra',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
