# Generated by Django 3.2.16 on 2022-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='mantras',
            field=models.ManyToManyField(to='core.Mantra'),
        ),
    ]
